/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adm;

import adm.trabajos.Trabajos;
import java.util.ArrayList;
import javax.swing.event.TreeModelListener;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author usuario
 */
public class IfTrabajos extends javax.swing.JInternalFrame {

    private class TrabajosTreeModel implements TreeModel {

        Trabajos trabajos;
        ArrayList<TreeModelListener> listeners = new ArrayList<>();

        public TrabajosTreeModel(Trabajos trabajos) {
            this.trabajos = trabajos;
        }

        @Override
        public Object getRoot() {
            return trabajos;
        }

        @Override
        public Object getChild(Object parent, int index) {
            if (parent instanceof Trabajos) {
                return ((Trabajos) parent).get(index);
            }
            return null;
        }

        @Override
        public int getChildCount(Object parent) {
            if (parent instanceof Trabajos) {
                return ((Trabajos) parent).size();
            }
            return 0;
        }

        @Override
        public boolean isLeaf(Object node) {
            if (node instanceof Trabajos) {
                return false;
            } else {
                return true;
            }
        }

        @Override
        public void valueForPathChanged(TreePath path, Object newValue) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public int getIndexOfChild(Object parent, Object child) {
            if (parent instanceof Trabajos) {
                return ((Trabajos) parent).indexOf(child);
            }
            return 0;
        }

        @Override
        public void addTreeModelListener(TreeModelListener l) {
            listeners.add(l);
        }

        @Override
        public void removeTreeModelListener(TreeModelListener l) {
            listeners.remove(l);
        }

    }

    private Trabajos trabajos;

    public IfTrabajos(Trabajos trabajos) {
        initComponents();
        setTrabajos(trabajos);
    }

    /**
     * @return the trabajos
     */
    public Trabajos getTrabajos() {
        return trabajos;
    }

    /**
     * @param trabajos the trabajos to set
     */
    public void setTrabajos(Trabajos trabajos) {
        this.trabajos = trabajos;
        tree.setModel(new TrabajosTreeModel(trabajos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();
        scrollPane = new javax.swing.JScrollPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("fkorkforfor");

        jSplitPane1.setDividerLocation(300);

        jScrollPane1.setViewportView(tree);

        jSplitPane1.setLeftComponent(jScrollPane1);
        jSplitPane1.setRightComponent(scrollPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables
}
